#!/usr/bin/env python3
import os
from pathlib import Path

BASE_DIR = Path(os.getenv("PWD", default="./"))
DATA_DIR = BASE_DIR / Path("data")
STATE_PIXEL_CONFIG_FILE = DATA_DIR / Path("pixel_locations.json")
METADATA_ZONE_CONFIG_FILE = DATA_DIR / Path("state_locations.txt")
ALL_TRUE = set([True])
SCORE_DIGIT_X_OFFSET = 19
SCORE_DIGIT_Y_OFFSET = 20
PERCENTAGE_DIGIT_X_OFFSET = 26
PERCENTAGE_DIGIT_Y_OFFSET = 18
BPM_DIGIT_X_OFFSET = 27
BPM_DIGIT_Y_OFFSET = 17

BPM_SP_1P_AREA_X_ORIGIN = 636
BPM_SP_1P_AREA_Y_ORIGIN = 644
BPM_SP_2P_AREA_X_ORIGIN = 566
BPM_SP_2P_AREA_Y_ORIGIN = 644
BPM_DP_AREA_X_ORIGIN = 601
BPM_DP_AREA_Y_ORIGIN = 643

MAX_BPM_SP_1P_AREA_X_ORIGIN = 726
MAX_BPM_SP_1P_AREA_Y_ORIGIN = 647
MAX_BPM_SP_2P_AREA_X_ORIGIN = 656
MAX_BPM_SP_2P_AREA_Y_ORIGIN = 647
MAX_BPM_DP_AREA_X_ORIGIN = 691
MAX_BPM_DP_AREA_Y_ORIGIN = 646

MIN_BPM_SP_1P_AREA_X_ORIGIN = 575
MIN_BPM_SP_1P_AREA_Y_ORIGIN = 647
MIN_BPM_SP_2P_AREA_X_ORIGIN = 505
MIN_BPM_SP_2P_AREA_Y_ORIGIN = 647
MIN_BPM_DP_AREA_X_ORIGIN = 540
MIN_BPM_DP_AREA_Y_ORIGIN = 646

MIN_MAX_BPM_DIGIT_X_OFFSET = 18
MIN_MAX_BPM_DIGIT_Y_OFFSET = 14

QUANTIZED_WHITE_MAX = 235
QUANTIZED_BLACK_MIN = 20
BRIGHTNESS_HALFWAY_POINT = 128
FAST_SLOW_X_OFFSET = 11
FAST_SLOW_Y_OFFSET = 11

LOG_FORMAT = "%(asctime)s:%(levelname)s:%(module)s:%(message)s"
DEV_MODE = True

# sqlite
APP_DB_NAME = "app.sqlite3.db"
USER_DB_NAME = "user.sqlite3.db"
APP_DB = DATA_DIR / Path(APP_DB_NAME)
USER_DB = DATA_DIR / Path(USER_DB_NAME)
MIN_APP_AGE_UPDATE_SECONDS = 43200
